resources:
  - name: cron_10min
    type: CronTrigger
    configuration:
      interval: "*/10 * * * *"

pipelines:
  - name: testing_123
#     configuration:
#       retentionPolicy:
#         maxAgeDays: 1
#         minRuns: 1
    steps:
      - name: myStep1
        type: Bash
        configuration:
#           retentionPolicy:
#             maxAgeDays: 2
#             minRuns: 1000
          inputResources: 
            - name: cron_10min
          integrations:
            - name: git_v
        execution:
          onExecute:
            - touch sample.txt
#             - echo test>sample.txt
#             - add_cache_files sample.txt sample
#             - add_run_variables sample:$run_id
