pipelines:
  - name: testSimple
    configuration:
      environmentVariables:
        readOnly:
          GO_VERSION: 1.18
          GO_VERSION: "1.18"
    steps:
      - name: testSimple
        type: Bash
        execution:
          onExecute:
            - printenv
