resources:
  - name: script_repo1
    type: GitRepo
    configuration:
      gitProvider: git_v
      path: vishnurao12/sample-script

pipelines:
  - name: test_stepTestReports
    steps:
      - name: testReport
        type: Bash
        configuration:
          inputResources:
            - name: script_repo1
        execution:
          onExecute:
            - write-output "Hi"
            - docker images
            - cd $res_script_resourcePath
            - python -m py_compile calc.py
            - pip install --upgrade pip
            - pip install pytest           
            - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
          onComplete:
            - save_tests $res_script_resourcePath/test-reports/results.xml
